import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Provider from "@/features/Provider";
import Footer from "@/widgets/auth/Footer";
import Header from "@/widgets/auth/Header";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Provider>
        <html lang="en">
          <body className={inter.className}>
            <div className="w-full h-full flex flex-col">
              <Header />
              <div className="grow">{children}</div>
              <Footer />
            </div>
          </body>
        </html>
      </Provider>
    </>
  );
}
