import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AuthProvider } from "@/features/AuthProvider";
import "./globals.css";
import { NavBar } from "@/widgets/NavBar";
import Provider from "@/features/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider>
      <AuthProvider>
        <html lang="en">
          <body className={inter.className}>
            <main className={"w-full h-full flex"}>
              <NavBar />
              {children}
            </main>
          </body>
        </html>
      </AuthProvider>
    </Provider>
  );
}
